version: '3.9'
services:
  backend:
    build:
      context: ..
      dockerfile: ./Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ../:/app
    environment:
      - NODE_ENV=development
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=eliech
      - DB_PASSWORD=Qwerty01!!
      - DB_NAME=Megurit
    depends_on:
      - mysql
    networks:
      - crud_network

  mysql:
    image: mysql:8.0
    container_name: mysql_container
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=Qwerty01!!
      - MYSQL_DATABASE=Megurit
      - MYSQL_USER=eliech
      - MYSQL_PASSWORD=Qwerty01!!
    networks:
      - crud_network

networks:
  crud_network:
    driver: bridge
